<?php
/**
 * Copyright (c) 2020, Nosto Solutions Ltd
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its contributors
 * may be used to endorse or promote products derived from this software without
 * specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @author Nosto Solutions Ltd <contact@nosto.com>
 * @copyright 2020 Nosto Solutions Ltd
 * @license http://opensource.org/licenses/BSD-3-Clause BSD 3-Clause
 *
 */

namespace Nosto\Cmp\Model\Search;

use Magento\Framework\Search\Request\BucketInterface as RequestBucketInterface;
use Magento\Framework\Search\Request\Dimension;
use Magento\Framework\Search\Request\QueryInterface;
use Magento\Framework\Search\RequestInterface;
use Magento\Framework\Search\Request as MagentoRequest;

class Request extends MagentoRequest implements RequestInterface
{

    /**
     * @var array
     */
    protected $postFilter;

    /**
     * @param string $name
     * @param string $indexName
     * @param QueryInterface $query
     * @param int|null $from
     * @param int|null $size
     * @param Dimension[] $dimensions
     * @param RequestBucketInterface[] $buckets
     * @param array $sort
     * @param array $postFilter
     */
    public function __construct($name, $indexName, QueryInterface $query, $from = null, $size = null, array $dimensions = [], array $buckets = [], $sort = [], $postFilter = [])
    {
        parent::__construct($name, $indexName, $query, $from, $size, $dimensions, $buckets, $sort);
        $this->postFilter = $postFilter;
    }

    /**
     * @return array
     */
    public function getPostFilter()
    {
        return $this->postFilter;
    }

    /**
     * @param array $postFilter
     */
    public function setPostFilter($postFilter): void
    {
        $this->postFilter = $postFilter;
    }

    public function getName()
    {
        return parent::getName();
    }

    public function getIndex()
    {
        return parent::getIndex();
    }

    public function getDimensions()
    {
        return parent::getDimensions();
    }

    public function getAggregation()
    {
        return parent::getAggregation();
    }

    public function getQuery()
    {
        return parent::getQuery();
    }

    public function getFrom()
    {
        return parent::getFrom();
    }

    public function getSize()
    {
        return parent::getSize();
    }

    public function getSort()
    {
        return parent::getSort(); // TODO: Change the autogenerated stub
    }
}
